import { createTypes } from 'reduxsauce'

export default createTypes(`
  CHANGE_DATA_DEGUSTATIONS
  ADD_DEGUSTATION
  SORT_DEGUSTATION_BY_MONTH
  SORT_DEGUSTATION_BY_QUARTER
  SORT_DEGUSTATION_BY_DAY
  SORT_DEGUSTATION_BY_YEAR

  GET_COFFEE_INIT
  GET_COFFEE_SUCCESS
  GET_COFFEE_FAILURE
  ADD_COFFEE_SUCCESS
  ADD_COFFEE_FAILURE

  GET_PORTION_INIT
  GET_PORTION_SUCCESS
  GET_PORTION_FAILURE
  ADD_PORTION_SUCCESS
  ADD_PORTION_FAILURE

  GET_PACK_INIT
  GET_PACK_SUCCESS
  GET_PACK_FAILURE
  ADD_PACK_SUCCESS
  ADD_PACK_FAILURE

  GET_DEGUSTATION_INIT
  GET_DEGUSTATION_SUCCESS
  GET_DEGUSTATION_FAILURE
  ADD_DEGUSTATION_SUCCESS
  ADD_DEGUSTATION_FAILURE

  CHANGE_DATA_OWNCUP
  ADD_OWNCUP
  SORT_OWNCUP_BY_MONTH
  SORT_OWNCUP_BY_DAY
  SORT_OWNCUP_BY_QUARTER
  SORT_OWNCUP_BY_YEAR

  CHANGE_DATA_OWNPACK
  ADD_OWNPACK
  SORT_OWNPACK_BY_MONTH
  SORT_OWNPACK_BY_DAY
  SORT_OWNPACK_BY_QUARTER
  SORT_OWNPACK_BY_YEAR

  CHANGE_DATA_INNERCUP
  ADD_INNERCUP
  SORT_INNERCUP_BY_MONTH
  SORT_INNERCUP_BY_DAY
  SORT_INNERCUP_BY_QUARTER
  SORT_INNERCUP_BY_YEAR

  CHANGE_DATA_INNERPACK
  ADD_INNERPACK
  SORT_INNERPACK_BY_MONTH
  SORT_INNERPACK_BY_DAY
  SORT_INNERPACK_BY_QUARTER
  SORT_INNERPACK_BY_YEAR

  SET_SIDEBAR_STATE
  SET_LOADER
  SET_INDEX_TAB
  SET_DATE_TRANSACTION
  SET_DATE_FILTER

  GET_USERS
  SET_CURRENT_USER
  GET_ERRORS
`, {})
