import { createTypes } from 'reduxsauce'

export default createTypes(`
  CHANGE_DATA_DEGUSTATIONS
  ADD_DEGUSTATION
  SORT_DEGUSTATION_BY_MONTH
  SORT_DEGUSTATION_BY_QUARTER
  SORT_DEGUSTATION_BY_DAY
  SORT_DEGUSTATION_BY_YEAR

  CHANGE_DATA_PACKS
  ADD_PACKS
  SORT_PACKS_BY_DAY
  SORT_PACKS_BY_MONTH
  SORT_PACKS_BY_QUARTER
  SORT_PACKS_BY_YEAR

  CHANGE_DATA_COFFEE
  ADD_COFFEE
  SORT_COFFEE_BY_DAY
  SORT_COFFEE_BY_MONTH
  SORT_COFFEE_BY_QUARTER
  SORT_COFFEE_BY_YEAR

  CHANGE_DATA_PORTION
  ADD_PORTION
  SORT_PORTION_BY_MONTH
  SORT_PORTION_BY_QUARTER
  SORT_PORTION_BY_DAY
  SORT_PORTION_BY_YEAR

  CHANGE_DATA_OWNCUP
  ADD_OWNCUP
  SORT_OWNCUP_BY_MONTH
  SORT_OWNCUP_BY_DAY
  SORT_OWNCUP_BY_QUARTER
  SORT_OWNCUP_BY_YEAR

  CHANGE_DATA_OWNPACK
  ADD_OWNPACK
  SORT_OWNPACK_BY_MONTH
  SORT_OWNPACK_BY_DAY
  SORT_OWNPACK_BY_QUARTER
  SORT_OWNPACK_BY_YEAR

  CHANGE_DATA_INNERCUP
  ADD_INNERCUP
  SORT_INNERCUP_BY_MONTH
  SORT_INNERCUP_BY_DAY
  SORT_INNERCUP_BY_QUARTER
  SORT_INNERCUP_BY_YEAR

  CHANGE_DATA_INNERPACK
  ADD_INNERPACK
  SORT_INNERPACK_BY_MONTH
  SORT_INNERPACK_BY_DAY
  SORT_INNERPACK_BY_QUARTER
  SORT_INNERPACK_BY_YEAR

  SET_SIDEBAR_STATE
  SET_LOADER
  SET_INDEX_TAB
  SET_DATE_TRANSACTION

  GET_USERS
  SET_CURRENT_USER
  GET_ERRORS
`, {})
