// Packs types
export const CHANGE_DATA_PACKS = 'CHANGE_DATA_PACKS';
export const ADD_PACKS = 'ADD_PACKS';
export const SORT_PACKS_BY_DAY = 'SORT_PACKS_BY_DAY';
export const SORT_PACKS_BY_MONTH = 'SORT_PACKS_BY_MONTH';
export const SORT_PACKS_BY_QUARTER = 'SORT_PACKS_BY_QUARTER';
export const SORT_PACKS_BY_YEAR = 'SORT_PACKS_BY_YEAR';


// User types
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERS = 'GET_USERS';


// Coffee types
export const CHANGE_DATA_COFFEE = 'CHANGE_DATA_COFFEE';
export const ADD_COFFEE = 'ADD_COFFEE';
export const SORT_COFFEE_BY_DAY = 'SORT_COFFEE_BY_DAY';
export const SORT_COFFEE_BY_MONTH = 'SORT_COFFEE_BY_MONTH';
export const SORT_COFFEE_BY_QUARTER = 'SORT_COFFEE_BY_QUARTER';
export const SORT_COFFEE_BY_YEAR = 'SORT_COFFEE_BY_YEAR';


// Portions types
export const CHANGE_DATA_PORTIONS = 'CHANGE_DATA_PORTIONS';
export const ADD_PORTION = 'ADD_PORTION';
export const SORT_PORTION_BY_MONTH = 'SORT_PORTION_BY_MONTH';
export const SORT_PORTION_BY_QUARTER = 'SORT_PORTION_BY_QUARTER';
export const SORT_PORTION_BY_DAY = 'SORT_PORTION_BY_DAY';
export const SORT_PORTION_BY_YEAR = 'SORT_PORTION_BY_YEAR';


// Portions types
export const CHANGE_DATA_DEGUSTATIONS = 'CHANGE_DATA_DEGUSTATIONS';
export const ADD_DEGUSTATION = 'ADD_DEGUSTATION';
export const SORT_DEGUSTATION_BY_MONTH = 'SORT_DEGUSTATION_BY_MONTH';
export const SORT_DEGUSTATION_BY_QUARTER = 'SORT_DEGUSTATION_BY_QUARTER';
export const SORT_DEGUSTATION_BY_DAY = 'SORT_DEGUSTATION_BY_DAY';
export const SORT_DEGUSTATION_BY_YEAR = 'SORT_DEGUSTATION_BY_YEAR';


// Innercups types
export const CHANGE_DATA_INNERCUPS = 'CHANGE_DATA_INNERCUPS'
export const ADD_INNERCUP = 'ADD_INNERCUP'
export const SORT_INNERCUP_BY_MONTH = 'SORT_INNERCUP_BY_MONTH'
export const SORT_INNERCUP_BY_DAY = 'SORT_INNERCUP_BY_DAY'
export const SORT_INNERCUP_BY_QUARTER = 'SORT_INNERCUP_BY_QUARTER'
export const SORT_INNERCUP_BY_YEAR = 'SORT_INNERCUP_BY_YEAR'


// Innerpacks types
export const CHANGE_DATA_INNERPACKS = 'CHANGE_DATA_INNERPACKS'
export const ADD_INNERPACK = 'ADD_INNERPACK'
export const SORT_INNERPACK_BY_MONTH = 'SORT_INNERPACK_BY_MONTH'
export const SORT_INNERPACK_BY_DAY = 'SORT_INNERPACK_BY_DAY'
export const SORT_INNERPACK_BY_QUARTER = 'SORT_INNERPACK_BY_QUARTER'
export const SORT_INNERPACK_BY_YEAR = 'SORT_INNERPACK_BY_YEAR'

// Owncups types
export const CHANGE_DATA_OWNCUPS = 'CHANGE_DATA_OWNCUPS'
export const ADD_OWNCUP = 'ADD_OWNCUP'
export const SORT_OWNCUP_BY_MONTH = 'SORT_OWNCUP_BY_MONTH'
export const SORT_OWNCUP_BY_DAY = 'SORT_OWNCUP_BY_DAY'
export const SORT_OWNCUP_BY_QUARTER = 'SORT_OWNCUP_BY_QUARTER'
export const SORT_OWNCUP_BY_YEAR = 'SORT_OWNCUP_BY_YEAR'

// Ownpacks types
export const CHANGE_DATA_OWNPACKS = 'CHANGE_DATA_OWNPACKS'
export const ADD_OWNPACK = 'ADD_OWNPACK'
export const SORT_OWNPACK_BY_MONTH = 'SORT_OWNPACK_BY_MONTH'
export const SORT_OWNPACK_BY_DAY = 'SORT_OWNPACK_BY_DAY'
export const SORT_OWNPACK_BY_QUARTER = 'SORT_OWNPACK_BY_QUARTER'
export const SORT_OWNPACK_BY_YEAR = 'SORT_OWNPACK_BY_YEAR'

// Settings types
export const SET_SIDEBAR_STATE = 'SET_SIDEBAR_STATE';
export const SET_LOADER = 'SET_LOADER';
export const SET_INDEX_TAB = 'SET_INDEX_TAB';
export const SET_DATE_TRANSACTION = 'SET_DATE_TRANSACTION';


export const CHANGE_DATA_OWN = 'CHANGE_DATA_OWN';
export const ADD_OWN = 'ADD_OWN';


export const SORT_OWN_BY_DAY = 'SORT_OWN_BY_DAY';
export const SORT_OWN_BY_MONTH = 'SORT_OWN_BY_MONTH';
export const SORT_OWN_BY_QUARTER = 'SORT_OWN_BY_QUARTER';
export const SORT_OWN_BY_YEAR = 'SORT_OWN_BY_YEAR';

