import { createTypes } from 'reduxsauce'

export default createTypes(`

  GET_COFFEE_INIT
  GET_COFFEE_SUCCESS
  GET_COFFEE_FAILURE
  ADD_COFFEE_SUCCESS
  ADD_COFFEE_FAILURE
  SELECT_COFFEE_ID

  GET_PORTION_INIT
  GET_PORTION_SUCCESS
  GET_PORTION_FAILURE
  ADD_PORTION_SUCCESS
  ADD_PORTION_FAILURE
  SELECT_PORTION_ID

  GET_PACK_INIT
  GET_PACK_SUCCESS
  GET_PACK_FAILURE
  ADD_PACK_SUCCESS
  ADD_PACK_FAILURE
  SELECT_PACK_ID

  LOG_IN_INIT
  LOG_IN_SUCCESS
  LOG_IN_FAILURE
  LOG_OUT

  SET_SIDEBAR_STATE
  SET_DATE_TRANSACTION
  SET_DATE_FILTER

  GET_USERS
  SET_CURRENT_USER
  GET_ERRORS
`, {})
